-- FIX para campos faltantes en productos (sin duplicar campos existentes)
-- Para Julia Confecciones - Concordancia VB6

-- 1. Agregar solo campos que no existen
ALTER TABLE productos ADD COLUMN IF NOT EXISTS cod_cole INTEGER;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS articulo INTEGER;

-- 2. Verificar estructura actual
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'productos'
ORDER BY ordinal_position;

-- 3. Crear tabla articulos (si no existe)
CREATE TABLE IF NOT EXISTS articulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    articulo INTEGER NOT NULL UNIQUE,
    descripcion VARCHAR(500) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Insertar articulos de ejemplo
INSERT INTO articulos (articulo, descripcion, categoria) VALUES
(1000, 'Polera Basica', 'POLERAS'),
(2000, 'Pantalon Escolar', 'PANTALONES'),
(3000, 'Chaqueta', 'CHAQUETAS'),
(4000, 'Falda Escolar', 'FALDAS'),
(5000, 'Buso', 'BUSOS')
ON CONFLICT (articulo) DO UPDATE SET descripcion = EXCLUDED.descripcion;

-- 5. Mostrar estructura final de productos
SELECT
    'Productos' as tabla,
    COUNT(*) as total_registros
FROM productos
UNION ALL
SELECT
    'Articulos' as tabla,
    COUNT(*) as total_registros
FROM articulos;

-- 6. Verificar campos nuevos en productos
SELECT
    id,
    codigo,
    nombre,
    descripcion,
    precio_venta,
    cod_cole,
    articulo
FROM productos
LIMIT 5;